version: "3.1"
services: 
    jenkins:
        image: jenkins/jenkins:lts
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        volumes: 
            - /data/jenkins:/var/jenkins_home
            - ./:/jenkins:ro
